[workspace]
members = [
  "backend",
  "crates/hermes-cli",
  "crates/hermes-client"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Shadow Team <ops@shadow.dev>"]


